
import { Question, EssayQuestion } from './types';

export const QUESTIONS: Question[] = [
  { id: 1, text: "Các phép tính đầu tiên được con người thực hiện bằng cách?", options: ["Sử dụng máy tính để bàn", "Sử dụng máy tính cầm tay", "Sử dụng 10 ngón tay", "Cả hai đáp án trên đều sai"], correctIndex: 2 },
  { id: 2, text: "Cách ghi số phổ biến từ xưa đến nay là?", options: ["Hệ thống ghi số la mã", "Hệ thống ghi số thập phân", "Hệ thống ghi số nguyên", "Cả ba đáp án trên đều đúng"], correctIndex: 1 },
  { id: 3, text: "Con người đã biết làm các phép tính số học từ bao giờ?", options: ["Hơn 1000 năm trước Công nguyên", "Hơn 1000 năm sau Công nguyên", "Hơn 2000 năm sau Công nguyên", "Hơn 2000 năm trước Công nguyên"], correctIndex: 3 },
  { id: 4, text: "Chiếc máy tính cơ học Pascal do ai sáng tạo ra?", options: ["Charles Babbage", "John Mauchly", "Blaise Pascal", "J. Presper Eckert"], correctIndex: 2 },
  { id: 5, text: "Sau Pascal, Gottfried Leibniz đã cải tiến thêm phép tính nào?", options: ["Phép chia và phép trừ", "Phép nhân và phép cộng", "Phép nhân và phép chia", "Phép nhân và phép trừ"], correctIndex: 2 },
  { id: 6, text: "Ai được coi là cha đẻ của công nghệ máy tính?", options: ["Charles Babbage", "Gottfried Leibniz", "John Mauchly", "Blaise Pascal"], correctIndex: 0 },
  { id: 7, text: "Ý tưởng nào đóng vai trò quan trọng nhất lịch sử phát triển máy tính?", options: ["Cơ giới hóa việc lao động", "Trí óc hóa việc tính toán", "Cơ giới hóa việc tính toán", "Đáp án khác"], correctIndex: 2 },
  { id: 8, text: "Nền tảng thiết kế các máy tính kĩ thuật số hiện đại là?", options: ["Cơ giới hóa việc tính toán", "Dùng rơ le thực hiện tính toán trên dãy bit", "Sáng tạo máy tính Pascal", "Cả ba đáp án trên đều sai"], correctIndex: 1 },
  { id: 9, text: "Thời kì đầu máy tính thiết kế dựa trên các rơ le gọi là?", options: ["Máy tính thông minh", "Máy tính hiện đại", "Máy tính khoa học", "Máy tính điện cơ"], correctIndex: 3 },
  { id: 10, text: "Năm 1943, Howard Aiken đã chế tạo thành công?", options: ["Máy tính cơ giới hóa", "Máy tính cơ học Pascal", "Máy tính điều khiển tuần tự tự động", "Đáp án khác"], correctIndex: 2 },
  { id: 11, text: "Đâu là đặc điểm của máy tính điện - cơ đa năng?", options: ["Hoạt động ít sự can thiệp của con người", "Phép cộng mất gần một giây", "Phép nhân mất khoảng 6 giây", "Tất cả các đáp án trên đều đúng"], correctIndex: 3 },
  { id: 12, text: "Nguyên lí 'chương trình được lưu trữ' có nội dung nào?", options: ["Lệnh lưu trong bộ nhớ như dữ liệu", "Chỉ cần tải chương trình vào bộ nhớ", "Nạp từ bộ nhớ vào bộ xử lí từng lệnh một", "Cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 13, text: "Theo nguyên lý 'chương trình lưu trữ', cấu tạo máy tính KHÔNG có?", options: ["Thiết bị ra", "Bộ xử lý", "Bộ nhớ", "Con chuột"], correctIndex: 3 },
  { id: 14, text: "Theo nguyên lý 'chương trình lưu trữ', cấu tạo của máy tính gồm?", options: ["Bộ xử lý, bộ nhớ", "Cổng kết nối vào - ra", "Đường truyền giữa các bộ phận", "Cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 15, text: "Công nghệ nào thay thế rơ le điện cơ?", options: ["Công nghệ cơ giới hóa", "Công nghệ tự động hóa", "Công nghệ đèn điện tử", "Đáp án khác"], correctIndex: 2 },
  { id: 16, text: "Bộ nhớ của máy tính thế hệ thứ nhất là?", options: ["Lõi từ lớn, đĩa từ", "Trống từ", "Lõi từ, băng từ", "Cả ba đều đúng"], correctIndex: 1 },
  { id: 17, text: "Các máy tính thế hệ thứ nhất có kích thước?", options: ["Nhỏ như máy để bàn", "Rất nhỏ cầm tay", "Rất lớn (chiếm một căn phòng)", "Lớn như những chiếc tủ"], correctIndex: 2 },
  { id: 18, text: "Đặc điểm của máy tính thế hệ thứ hai là?", options: ["Dùng bóng bán dẫn", "Bộ nhớ lõi từ, băng từ", "Thiết bị vào-ra: máy đọc in băng đục lỗ", "Cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 19, text: "Các máy tính thế hệ thứ hai có kích thước?", options: ["Chiếm một căn phòng", "Lớn như những chiếc tủ", "Nhỏ như máy để bàn", "Rất nhỏ cầm tay"], correctIndex: 1 },
  { id: 20, text: "Thành phần điện tử chính máy tính thế hệ thứ ba là?", options: ["Mạch tích hợp (IC)", "Bóng bán dẫn", "Đèn điện tử", "Bóng chân không"], correctIndex: 0 },
  { id: 21, text: "Mạch tích hợp cỡ siêu lớn (VLSI) là?", options: ["Hàng chục triệu linh kiện trên một mạch", "Chứa hàng triệu linh kiện", "Bóng bán dẫn", "Đáp án khác"], correctIndex: 0 },
  { id: 22, text: "Máy tính điện tử có mấy thế hệ?", options: ["Ba thế hệ", "Năm thế hệ", "Bốn thế hệ", "Hai thế hệ"], correctIndex: 1 },
  { id: 23, text: "Năm thế hệ máy tính được đánh dấu bởi?", options: ["Tiến bộ công nghệ", "Khả năng kết nối", "Tiêu thụ ít năng lượng", "Cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 24, text: "Máy tính đã thay đổi theo cách nào?", options: ["Nhỏ gọn, mạnh mẽ hơn", "Thông minh vượt bậc", "Hỗ trợ con người mọi lĩnh vực", "Cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 25, text: "Bộ xử lý hiện nay dựa trên công nghệ nào?", options: ["Đèn điện tử", "Bóng bán dẫn đơn", "Mạch tích hợp cỡ lớn (VLSI)", "Mạch tích hợp đơn giản"], correctIndex: 2 },
  { id: 26, text: "Bức ảnh số khác với ảnh trên giấy ở điểm nào?", options: ["Không tốn vật liệu", "Gửi đi vẫn giữ được bản gốc", "Cả hai đáp án trên đều đúng", "Cả hai đáp án trên đều sai"], correctIndex: 2 },
  { id: 27, text: "Thông tin mã hóa thành gì để chuyển vào máy tính?", options: ["Số liệu", "Dãy bit", "Hình ảnh", "Văn bản"], correctIndex: 1 },
  { id: 28, text: "Thông tin số là thông tin mã hóa thành dãy bit và...?", options: ["Lưu trong đĩa", "Lan truyền trao đổi trong môi trường kĩ thuật số", "Chỉ dùng cho di động", "Đáp án khác"], correctIndex: 1 },
  { id: 29, text: "Đặc điểm của thông tin số là gì?", options: ["Dùng không cần mạng", "Dựa trên giấy", "Có thể truy cập từ xa qua Internet", "Đáp án khác"], correctIndex: 2 },
  { id: 30, text: "Đâu KHÔNG phải là đặc điểm của thông tin số?", options: ["Truy cập từ xa", "Dễ nhân bản và chia sẻ", "Chỉ có thể truy cập ở khoảng cách gần", "Lan truyền tự động"], correctIndex: 2 },
  { id: 31, text: "Thông tin số có thể truy cập từ xa nếu?", options: ["Người quản lý cho phép", "Có sóng Wifi mạnh", "Ít dữ liệu", "Đáp án khác"], correctIndex: 0 },
  { id: 32, text: "Thông tin số có thể làm gì?", options: ["Lưu trữ khổng lồ", "Cấp quyền truy cập linh hoạt", "Cả hai đáp án trên đều đúng", "Cả hai đều sai"], correctIndex: 2 },
  { id: 33, text: "Mức độ tin cậy của thông tin số phụ thuộc vào?", options: ["Nguồn gốc", "Mục tiêu thông tin", "Cả hai đáp án trên đều đúng", "Cả hai đều sai"], correctIndex: 2 },
  { id: 34, text: "Thông tin số có những ưu điểm gì?", options: ["Dễ tìm kiếm, xử lý", "Được pháp luật bảo hộ quyền tác giả", "Có thể kiểm tra độ tin cậy", "Cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 35, text: "Biểu hiện tự chủ trong các mối quan hệ là gì?", options: ["Chủ động thiết lập bạn bè", "Kiểm soát cảm xúc", "Chịu trách nhiệm hành động", "Cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 36, text: "Đâu là thông tin không đáng tin cậy?", options: ["Tin đồn thổi", "Tin lừa dối", "Tin thiếu kiểm chứng", "Tất cả các đáp án trên đều đúng"], correctIndex: 3 },
  { id: 37, text: "Điều gì ảnh hưởng đến độ tin cậy của thông tin?", options: ["Uy tín tổ chức cung cấp", "Uy tín cá nhân cung cấp", "Cả hai đáp án trên đều đúng", "Cả hai đều sai"], correctIndex: 2 },
  { id: 38, text: "Độ tin cậy của ý kiến thấp hơn sự kiện vì?", options: ["Mang nhiều cảm xúc", "Mang định kiến cá nhân", "Cả hai đáp án trên đều đúng", "Cả hai đều sai"], correctIndex: 2 },
  { id: 39, text: "Điều gì quyết định thông tin còn ý nghĩa hay không?", options: ["Sự chính xác", "Tính thời sự (thời điểm công bố)", "Tính sự kiện", "Cách trình bày"], correctIndex: 1 },
  { id: 40, text: "Cách xác định thông tin tin cậy là?", options: ["Kiểm tra nguồn tin", "Phân biệt ý kiến/sự kiện", "Kiểm tra chứng cứ và tính thời sự", "Cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 41, text: "Thông tin đáng tin cậy giúp chúng ta?", options: ["Kết luận đúng", "Hành động đúng", "Giải quyết vấn đề", "Cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 42, text: "Thông tin số được lưu trữ khổng lồ và...?", options: ["Dễ bị mất", "Được bảo hộ quyền tác giả và rất đáng tin cậy", "Khó truy cập", "Đáp án khác"], correctIndex: 1 },
  { id: 43, text: "Khi đưa ảnh lên mạng xã hội cá nhân, ai được xem?", options: ["Bạn bè đời thực", "Tất cả mọi người", "Những người trong danh sách bạn bè", "Cả ba đều sai"], correctIndex: 2 },
  { id: 44, text: "Đặc điểm chính của thông tin số là?", options: ["Dễ nhân bản, lan truyền", "Khó xóa bỏ hoàn toàn", "Truy cập từ xa khi được phép", "Cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 45, text: "Thông tin nào có độ tin cậy THẤP nhất?", options: ["Tin thời sự vừa đăng", "Web cập nhật hàng giờ", "Web đã lâu không cập nhật", "Báo chính thống"], correctIndex: 2 },
  { id: 46, text: "Thông tin có độ tin cậy thấp là tin?", options: ["Không có chứng cứ", "Mang tính cá nhân", "Bị cũ, lâu ngày", "Cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 47, text: "Tìm hiểu cách dùng máy ảnh mới, nên xem nguồn nào?", options: ["Bạn bè", "Người giỏi Tin học", "Hướng dẫn của nhà sản xuất", "Diễn đàn mạng"], correctIndex: 2 },
  { id: 48, text: "Tìm hiểu đội bóng châu Phi, nguồn nào tin cậy nhất?", options: ["Fan club", "Liên đoàn bóng đá châu Phi", "CLB đối thủ", "Báo lá cải"], correctIndex: 1 },
  { id: 49, text: "Thông tin xuất hiện năm nào tin cậy hơn (trong đề)?", options: ["2020", "2021", "2023", "2022"], correctIndex: 2 },
  { id: 50, text: "Lựa chọn thông tin trình bày cần?", options: ["Phù hợp nội dung", "Nguồn tin cậy", "Đã kiểm chứng", "Cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 51, text: "Loại thông tin KHÔNG nên lựa chọn?", options: ["Tin mới cập nhật", "Tin đã kiểm chứng", "Nguồn tin không rõ ràng", "Tin phù hợp chủ đề"], correctIndex: 2 },
  { id: 52, text: "Nguồn thông tin KHÔNG nên tin tưởng?", options: ["Người ẩn danh trên Facebook", "Cộng đồng chuyên môn", "Web chính phủ", "Bộ Công Thương"], correctIndex: 0 },
  { id: 53, text: "Phương tiện kỹ thuật để chia sẻ bài thuyết trình?", options: ["Email", "Mạng xã hội", "Google Drive/Lưu trữ đám mây", "Cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 54, text: "Tìm hiểu phương pháp học tốt nên xem tin từ?", options: ["Người lạ", "Người học giỏi nổi tiếng", "Người mới quen trên mạng", "Ai cũng được"], correctIndex: 1 },
  { id: 55, text: "Tìm hiểu năng lượng gió, nguồn nào tin cậy nhất?", options: ["Web ẩn danh", "Báo cũ", "Web chính phủ mới nhất", "Đáp án khác"], correctIndex: 2 },
  { id: 56, text: "Hình thành ý tưởng dựa trên thông tin?", options: ["Người lạ", "Tin đăng lâu", "Tin chính xác đã kiểm chứng", "Tin giật gân"], correctIndex: 2 },
  { id: 57, text: "Bức ảnh số ưu việt hơn ảnh giấy ở?", options: ["Không tốn giấy mực", "Gửi đi vẫn giữ được ảnh", "Cả hai đáp án trên đều đúng", "Cả hai đều sai"], correctIndex: 2 },
  { id: 58, text: "Thông tin số là thông tin mã hóa dãy bit và...?", options: ["Lưu trong máy", "Lan truyền trong môi trường kĩ thuật số", "Chỉ dùng cho web", "Đáp án khác"], correctIndex: 1 },
  { id: 59, text: "Thông tin nào ĐÁNG tin cậy nhất?", options: ["Tin trên web lạ", "Tin từ người ẩn danh", "Web Bộ Y Tế năm 2023", "Tin đồn"], correctIndex: 2 },
  { id: 60, text: "Thông tin số truy cập từ xa được nếu?", options: ["Người quản lý cho phép", "Có Internet", "Ít dữ liệu", "Đáp án khác"], correctIndex: 0 },
  { id: 61, text: "Khi tìm kiếm thông tin cần?", options: ["Tìm tin không nguồn gốc", "Tìm tin có nguồn gốc rõ ràng", "Tìm tin đăng từ lâu", "Tìm tin nhiều like"], correctIndex: 1 },
  { id: 62, text: "Chọn tin cho bài thuyết trình năng lượng?", options: ["Bài Facebook ẩn danh", "Web Cộng đồng Cơ điện Lạnh VN", "Cả hai đều đúng", "Cả hai đều sai"], correctIndex: 1 },
  { id: 63, text: "Độ tin cậy thông tin số phụ thuộc?", options: ["Nguồn gốc", "Mục tiêu tin", "Cả hai đáp án trên đều đúng", "Cả hai đều sai"], correctIndex: 2 },
  { id: 64, text: "Chúng ta KHÔNG nên?", options: ["Dùng tin cậy cao", "Dùng tin độ tin cậy thấp", "Cả hai đều sai", "Cả hai đều đúng"], correctIndex: 1 },
  { id: 65, text: "Con người làm tính đầu tiên bằng gì?", options: ["Máy tính", "Ngón tay", "Bàn tính", "Cành cây"], correctIndex: 1 },
  { id: 66, text: "Yếu tố ảnh hưởng giá trị thông tin?", options: ["Thẩm quyền tổ chức", "Thẩm quyền cá nhân", "Cả hai đáp án trên đều đúng", "Cả hai đều sai"], correctIndex: 2 },
  { id: 67, text: "Công nghệ số tiềm ẩn vấn nạn gì?", options: ["Vi phạm đạo đức", "Vi phạm pháp luật", "Thiếu văn hóa", "Cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 68, text: "Biểu hiện vi phạm khi dùng công nghệ số?", options: ["Quay trộm phim", "Chụp ảnh nơi cấm", "Ghi âm trái phép", "Cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 69, text: "Hành vi vi phạm đạo đức số em có thể gặp?", options: ["Đạo văn (sao chép web)", "Dùng phần mềm lậu", "Phát tán video bạo lực", "Cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 70, text: "Để tránh vi phạm công nghệ số em cần?", options: ["Học kiến thức pháp luật", "Dùng hàng có bản quyền", "Tôn trọng tác giả", "Cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 71, text: "Bạn rủ vào nhóm kín mạng xã hội lạ em sẽ?", options: ["Vào ngay", "Hỏi kỹ rồi mới quyết định", "Chấp nhận vì là bạn rủ", "Báo công an"], correctIndex: 1 },
  { id: 72, text: "Hành động KHÔNG vi phạm pháp luật?", options: ["Tặng đĩa nhạc bản quyền đã mua cho bạn", "Đăng tin giả", "Ghi âm lén", "Tải bài người khác dùng làm của mình"], correctIndex: 0 },
  { id: 73, text: "Sản phẩm số em có thể tạo ra?", options: ["Ảnh chụp", "Truyện tự sáng tác", "Bài đăng MXH", "Cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 74, text: "Em có thể tạo ra sản phẩm số nào?", options: ["Ghi âm giọng hát", "Vlog", "Game tự thiết kế", "C cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 75, text: "Tạo sản phẩm số dễ dàng nhờ?", options: ["Công nghệ kĩ thuật số", "Thiết bị thông minh", "C cả hai đáp án trên đều đúng", "C cả hai đều sai"], correctIndex: 2 },
  { id: 76, text: "Vì sao cần bảo vệ sản phẩm số cá nhân?", options: ["Thể hiện đạo đức", "Thể hiện tính văn hóa", "Đúng pháp luật", "C cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 77, text: "Chú ý khi tạo sản phẩm số?", options: ["Trung thực", "Dùng tin tự tạo", "Tuân thủ văn hóa xã hội", "Tất cả đáp án trên đều đúng"], correctIndex: 3 },
  { id: 78, text: "Biểu hiện tự chủ trên MXH?", options: ["Bình luận tích cực", "Xác minh tin trước khi share", "Từ chối kết bạn lạ", "C cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 79, text: "Biểu hiện trung thực khi tạo sản phẩm số?", options: ["Không dùng tin giả", "Không dùng tin thiếu tin cậy", "Không đạo văn", "C cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 80, text: "Sản phẩm số nên tuân thủ?", options: ["Ngôn ngữ lịch sự", "Ảnh văn minh", "Bảo mật tin cá nhân", "C cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 81, text: "Chúng ta cần làm gì khi dùng MXH?", options: ["Bảo đảm văn hóa", "Tuân thủ pháp luật", "Tránh tin sai trái", "C cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 82, text: "Em có thể dùng tin nào tự tạo?", options: ["Video tự quay", "Ảnh tự chụp", "Nội dung tự viết", "C cả ba đều đúng"], correctIndex: 3 },
  { id: 83, text: "Đảm bảo văn hóa số giúp gì?", options: ["Tránh tin sai", "Xã hội số lành mạnh", "C cả hai đều đúng", "C cả hai đều sai"], correctIndex: 2 },
  { id: 84, text: "Hành động vi phạm đạo đức số là?", options: ["Chia sẻ kinh nghiệm học tập", "Sáng tác thơ", "Lan truyền video bạo lực học đường", "Dùng web học tập"], correctIndex: 2 },
  { id: 85, text: "Hành động KHÔNG vi phạm là?", options: ["Dùng web phim lậu", "Cá cược bóng đá", "Tạo blog chia sẻ kiến thức", "Quay trộm bạn"], correctIndex: 2 },
  { id: 86, text: "Bạn quay video bạo lực đăng MXH em sẽ?", options: ["Khuyên gửi cho mọi người", "Khuyên không nên quay/đăng vì vi phạm quyền riêng tư", "Cổ vũ bạn", "Lờ đi"], correctIndex: 1 },
  { id: 87, text: "Ưu điểm nổi bật bảng tính là?", options: ["Thủ công", "Tự động", "Chính xác", "Cả 2 và 3"], correctIndex: 1 },
  { id: 88, text: "Bảng tính tự động nhờ đâu?", options: ["Tính toán siêu nhanh", "Tính theo địa chỉ ô", "Nhiều hàm phức tạp", "C cả ba đều đúng"], correctIndex: 1 },
  { id: 89, text: "Địa chỉ ô trong bảng tính gồm?", options: ["Tương đối", "Tuyệt đối", "Hỗn hợp", "C cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 90, text: "Địa chỉ tương đối có đặc điểm?", options: ["Không thay đổi", "Tự động thay đổi để giữ vị trí tương đối", "Thay đổi ngẫu nhiên", "Đáp án khác"], correctIndex: 1 },
  { id: 91, text: "Địa chỉ ô không đổi khi sao chép gọi là?", options: ["Tương đối", "Tuyệt đối", "Hỗn hợp", "Địa chỉ chết"], correctIndex: 1 },
  { id: 92, text: "Ký hiệu địa chỉ tuyệt đối?", options: ["$", "&", "#", "%"], correctIndex: 0 },
  { id: 93, text: "Địa chỉ nào là tuyệt đối chuẩn?", options: ["$J2", "J$2", "$J$2", "J2"], correctIndex: 2 },
  { id: 94, text: "Phím chuyển đổi địa chỉ ô?", options: ["F2", "F3", "F4", "F1"], correctIndex: 2 },
  { id: 95, text: "Trong công thức Doanh thu = Đơn giá * Số lượng, giá trị thay đổi là?", options: ["Tỉ lệ", "Doanh thu", "Đơn giá", "Tất cả"], correctIndex: 1 },
  { id: 96, text: "Trong công thức tính thuế = Doanh thu * Tỉ lệ thuế, giá trị cố định là?", options: ["Tỉ lệ thuế", "Doanh thu", "Số tiền thuế", "C cả ba đều đúng"], correctIndex: 0 },
  { id: 97, text: "Địa chỉ tuyệt đối đặc trưng bởi?", options: ["Luôn thay đổi", "Không thay đổi khi sao chép", "Chỉ dùng cho số", "Đáp án khác"], correctIndex: 1 },
  { id: 98, text: "Lệnh sao chép dữ liệu?", options: ["Cut", "Copy", "Paste", "Delete"], correctIndex: 1 },
  { id: 99, text: "Công thức doanh thu chuẩn là?", options: ["Cộng", "Trừ", "Nhân (Đơn giá x Số lượt)", "Chia"], correctIndex: 2 },
  { id: 100, text: "Sao chép E4 xuống E5 thì?", options: ["Địa chỉ không đổi", "Địa chỉ tự thay đổi tương ứng", "Lỗi công thức", "Xóa sạch"], correctIndex: 1 },
  { id: 101, text: "Sao chép =C4*D4 xuống hàng 5 sẽ là?", options: ["=C4*D5", "=C5*D4", "=C5*D5", "Giữ nguyên"], correctIndex: 2 },
  { id: 102, text: "Địa chỉ tương đối là?", options: ["C4", "D4", "E4", "C cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 103, text: "Sao chép E4 xuống E6, công thức thành?", options: ["=C5*D5", "=C6*D6", "=C4*D4", "=C6*D4"], correctIndex: 1 },
  { id: 104, text: "Sao chép E4 đến E7, công thức thành?", options: ["=C7*D7", "=C4*D4", "=C7*D4", "=C4*D7"], correctIndex: 0 },
  { id: 105, text: "Sao chép E4 đến E8, công thức thành?", options: ["=C8*D8", "=C4*D4", "=C8*D4", "=C4*D8"], correctIndex: 0 },
  { id: 106, text: "Sao chép E4 đến E9, công thức thành?", options: ["=C9*D9", "=C4*D4", "=C9*D4", "=C4*D9"], correctIndex: 0 },
  { id: 107, text: "Bảng mã KHÔNG hoàn toàn chuẩn thứ tự tiếng Việt?", options: ["Unicode", "VNI", "Telex", "TCVN3"], correctIndex: 0 },
  { id: 108, text: "Sắp xếp và lọc giúp gì?", options: ["Theo bảng chữ cái", "Chọn dữ liệu giống nhau", "Tìm tin theo ô", "C cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 109, text: "Lệnh sắp xếp dữ liệu?", options: ["Filter", "Data", "Sort", "Sort & Filter"], correctIndex: 2 },
  { id: 110, text: "Thẻ chứa lệnh Sort?", options: ["Home", "Data", "Insert", "Page Layout"], correctIndex: 1 },
  { id: 111, text: "Thêm tiêu chí sắp xếp chọn?", options: ["Add Level", "Copy Level", "Delete Level", "New Level"], correctIndex: 0 },
  { id: 112, text: "Tránh sắp xếp cả dòng tiêu đề chọn?", options: ["My data has headers", "Headers Only", "Lock Title", "Skip Row 1"], correctIndex: 0 },
  { id: 113, text: "Xóa tiêu chí sắp xếp chọn?", options: ["Clear", "Delete Level", "Remove", "Reset"], correctIndex: 1 },
  { id: 114, text: "Chức năng lọc dùng để?", options: ["Sắp xếp lại", "Chỉ hiển thị dòng thỏa mãn điều kiện", "Xóa dòng sai", "Đếm dữ liệu"], correctIndex: 1 },
  { id: 115, text: "Để lọc dữ liệu chọn?", options: ["Sort", "Filter", "Filter & Sort", "Data"], correctIndex: 1 },
  { id: 116, text: "Bỏ lọc toàn bộ chọn?", options: ["Select All", "Clear Filter", "Delete Filter", "Show All"], correctIndex: 0 },
  { id: 117, text: "Dữ liệu không thỏa điều kiện lọc sẽ?", options: ["Bị xóa", "Bị ẩn đi", "Đổi màu", "Giữ nguyên"], correctIndex: 1 },
  { id: 118, text: "Number Filters xuất hiện khi cột chứa?", options: ["Ký tự", "Số", "Hình ảnh", "Ngày tháng"], correctIndex: 1 },
  { id: 119, text: "Text Filters xuất hiện khi cột chứa?", options: ["Số", "Ký tự", "Màu sắc", "Phông chữ"], correctIndex: 1 },
  { id: 120, text: "Bảng khảo sát nên có cột?", options: ["STT", "Họ và tên", "Nội dung", "C cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 121, text: "Cột STT thường là dạng?", options: ["Chữ", "Số", "Ngày", "Tiền"], correctIndex: 1 },
  { id: 122, text: "Cột Họ và tên là dạng?", options: ["Số", "Chữ (Text)", "Ký hiệu", "Boolean"], correctIndex: 1 },
  { id: 125, text: "Tiêu chí sắp xếp bảng chữ cái chuẩn là?", options: ["Sắp xếp tên theo UNICODE", "Sắp theo STT", "Sắp theo Tổ", "Sắp ngẫu nhiên"], correctIndex: 0 },
  { id: 126, text: "Vùng dữ liệu sắp xếp chuẩn (hàng 2 là tiêu đề, 12 hàng tổng)?", options: ["A1:E12", "A2:E12", "A3:E12", "A1:E11"], correctIndex: 1 },
  { id: 127, text: "Hàng tiêu đề trong vùng A2:E12 là?", options: ["Hàng 1", "Hàng 2", "Hàng 3", "Hàng cuối"], correctIndex: 1 },
  { id: 128, text: "Hàng dữ liệu thực sự cần sắp xếp trong A2:E12 là?", options: ["Hàng 2-12", "Hàng 3-12", "Hàng 1-12", "Hàng 3-11"], correctIndex: 1 },
  { id: 129, text: "Biểu đồ dùng để làm gì?", options: ["Trực quan hóa dữ liệu", "Dễ so sánh", "Dự đoán xu hướng", "C cả ba đáp án trên đều đúng"], correctIndex: 3 },
  { id: 130, text: "Biểu đồ CỘT dùng để?", options: ["So sánh các đại lượng", "Theo dõi xu hướng", "Xem tỉ lệ phần trăm", "Vẽ trang trí"], correctIndex: 0 },
  { id: 131, text: "Biểu đồ ĐOẠN THẲNG dùng để?", options: ["So sánh", "Xem xu hướng tăng giảm theo thời gian", "Xem tỉ lệ", "Cả 1 và 2"], correctIndex: 1 },
  { id: 132, text: "Biểu đồ HÌNH QUẠT TRÒN dùng để?", options: ["So sánh nhiều phần", "So sánh các phần với tổng thể", "Xem xu hướng", "Đáp án khác"], correctIndex: 1 },
  { id: 133, text: "Biểu đồ là cách minh họa dữ liệu...?", options: ["Phức tạp", "Trực quan", "Trừu tượng", "Khó hiểu"], correctIndex: 1 },
  { id: 134, text: "Biểu đồ giúp người xem...?", options: ["Dễ so sánh", "Nhận định xu hướng", "C cả hai đáp án trên đều đúng", "C cả hai đều sai"], correctIndex: 2 },
  { id: 135, text: "Lựa chọn biểu đồ phụ thuộc vào?", options: ["Màu sắc", "Mục đích biểu diễn dữ liệu", "Độ khó", "Kích thước bảng"], correctIndex: 1 },
  { id: 136, text: "Tình huống nào nên dùng biểu đồ?", options: ["Lượng mưa các tháng trong năm", "Định nghĩa máy tính", "Lịch sử loài người", "Tất cả đều sai"], correctIndex: 0 },
  { id: 137, text: "Tình huống KHÔNG cần biểu đồ?", options: ["Lượng mưa", "Chiều cao lớp", "Khái niệm máy tính để bàn", "Tỉ lệ dân số"], correctIndex: 2 },
  { id: 138, text: "Lệnh tạo biểu đồ cột?", options: ["Insert Pie", "Insert Column or Bar Chart", "Insert Line", "Scatter Plot"], correctIndex: 1 },
  { id: 139, text: "Lệnh Insert Chart nằm trong thẻ nào?", options: ["Home", "Data", "Insert", "Design"], correctIndex: 2 },
  { id: 140, text: "Biểu đồ cột thuộc nhóm lệnh nào?", options: ["2-D Column", "2-D Pie", "3-D Line", "Bar"], correctIndex: 0 },
  { id: 141, text: "Biểu đồ tròn thuộc nhóm lệnh nào?", options: ["2-D Pie", "2-D Column", "Circular", "Bubble"], correctIndex: 0 },
  { id: 142, text: "Lệnh tạo biểu đồ tròn?", options: ["Insert Pie", "Doughnut", "C cả hai đáp án trên đều đúng", "C cả hai đều sai"], correctIndex: 2 },
  { id: 143, text: "Biểu đồ tròn mặc định có?", options: ["Tiêu đề", "Chú giải", "C cả hai đáp án trên đều đúng", "C cả hai đều sai"], correctIndex: 2 },
  { id: 144, text: "So sánh tỉ lệ % học sinh trên tổng thể dùng?", options: ["Cột", "Đoạn thẳng", "Hình quạt tròn", "Điểm"], correctIndex: 2 },
  { id: 145, text: "Thể hiện số lượng học sinh dùng biểu đồ?", options: ["Cột", "Tròn", "Lưới", "Phễu"], correctIndex: 0 },
  { id: 146, text: "Doanh thu 2016-2020 tăng từ 3036 lên 5439 là?", options: ["Doanh thu tăng mạnh", "Doanh thu giảm", "Doanh thu ổn định", "Đáp án khác"], correctIndex: 0 },
  { id: 147, text: "Cơ cấu diện tích lúa theo mùa nên dùng?", options: ["Hình quạt tròn", "Cột", "Đường", "Area"], correctIndex: 0 },
  { id: 148, text: "Để minh họa tỉ lệ phần trăm các mùa lúa dùng?", options: ["Biểu đồ tròn", "Biểu đồ cột", "Biểu đồ đường", "Biểu đồ điểm"], correctIndex: 0 }
];

export const ESSAY_QUESTIONS: EssayQuestion[] = [
  { id: 1, category: "Đạo đức & Pháp luật", text: "Tình huống: Lan chụp ảnh sách gửi Nam, Nam dùng Word gõ lại nộp bài. Ai vi phạm? Khuyên gì?", suggestedAnswer: "Lan vi phạm bản quyền khi phát tán nội dung sách. Nam vi phạm đạo đức học tập khi sao chép bài người khác. Lời khuyên: Lan nên tôn trọng bản quyền; Nam nên tự làm bài." },
  { id: 2, category: "Bảng tính", text: "Lợi ích của việc sắp xếp và lọc dữ liệu?", suggestedAnswer: "Giúp tìm kiếm nhanh, tổ chức dữ liệu khoa học, dễ dàng so sánh và phân tích để đưa ra báo cáo chính xác." },
  { id: 3, category: "Biểu đồ", text: "Nêu một số tình huống thực tế cần tạo biểu đồ?", suggestedAnswer: "So sánh điểm các tổ, theo dõi nhiệt độ hàng tuần, xem cơ cấu chi tiêu tháng, so sánh dân số." },
  { id: 4, category: "Văn bản", text: "Nêu các bước tạo danh sách có thứ tự (Numbering)?", suggestedAnswer: "1. Chọn văn bản. 2. Thẻ Home -> Paragraph. 3. Chọn lệnh Numbering và kiểu mong muốn." },
  { id: 5, category: "Bảng tính", text: "Cách tính điểm TB 4 môn Toán, Văn, Anh, Tin của 5 bạn?", suggestedAnswer: "Dùng hàm =AVERAGE(Toán:Tin) hoặc công thức =(Toán+Văn+Anh+Tin)/4 rồi kéo Fill Handle." },
  { id: 6, category: "Biểu đồ", text: "Ý nghĩa của biểu đồ Cột, Đoạn thẳng, Hình quạt tròn?", suggestedAnswer: "Cột: So sánh. Đoạn thẳng: Xu hướng. Quạt tròn: Tỉ lệ so với tổng thể." }
];
